# Generated by Django 6.0.4 on 2026-05-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_organization'),
        ('employees', '0011_officelocationsettings_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyannouncement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='employees.organization'),
        ),
    ]
