# Generated by Django 6.0.4 on 2026-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_announcement_publish_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Alternate email for receiving platform notifications (used by Super Admins).', max_length=254, null=True),
        ),
    ]
