# Generated by Django 6.0.4 on 2026-10-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_actionlog'),
        ('employees', '0034_organization_attendance_anomaly_backdate_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='employees.organization'),
        ),
    ]
