# Generated by Django 6.0.4 on 2026-10-05 10:00

from django.db import migrations


def backfill_organization(apps, schema_editor):
    ActionLog = apps.get_model('accounts', 'ActionLog')
    
    # Process in batches to avoid memory issues if there are many logs
    logs_to_update = []
    
    for log in ActionLog.objects.filter(user__isnull=False, organization__isnull=True).select_related('user'):
        if log.user.organization_id:
            log.organization_id = log.user.organization_id
            logs_to_update.append(log)
            
    if logs_to_update:
        ActionLog.objects.bulk_update(logs_to_update, ['organization'])

def reverse_backfill(apps, schema_editor):
    pass # No need to reverse, the field itself would be dropped if reversed to 0012

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_actionlog_organization'),
    ]

    operations = [
        migrations.RunPython(backfill_organization, reverse_backfill),
    ]
