export const LEAVE_RULE_FIELD_HINTS = {
  name: 'Display name shown to employees when applying leave.',
  description: 'Optional notes about when and how this leave type should be used.',
  short_name: 'Short code used in tags and reports (e.g. PL, CL, SL).',
  annual_quota: 'Maximum leave days credited per calendar year.',
  count_weekends: 'If enabled, weekends between the start and end date count as leave days.',
  count_holidays: 'If enabled, holidays between the start and end date count as leave days.',
  accrual_basis: 'Leave balance is credited based on accrual schedule instead of upfront.',
  present_day_basis: 'Leave is credited only for days the employee was present.',
  accrual_frequency: 'How often leave balance is credited (monthly, half yearly, or yearly).',
  accrual_period: 'Whether accrual credits at the start or end of the period.',
  allowed_under_probation: 'Employees on probation can apply this leave type.',
  allowed_under_notice: 'Employees serving notice period can apply this leave type.',
  probation_quota: 'Annual quota used while the employee is on probation.',
  encash_enabled: 'Unused balance can be encashed at year-end or on exit.',
  carry_forward_enabled: 'Unused balance can be carried forward to the next year.',
  max_per_month: 'Maximum number of leave days allowed in a single month.',
  continuous_allowed: 'Maximum consecutive days allowed in one leave request.',
  negative_allowed: 'Employee can apply leave even when balance is zero (goes negative).',
  future_dated_allowed: 'Employees can apply leave for future dates.',
  future_dated_after_days: 'How many days ahead future-dated leave can be applied.',
  backdated_allowed: 'Employees can apply leave for past dates.',
  backdated_up_to_days: 'How many days back leave can be applied.',
  apply_next_year_until_month: 'Until which month employees can apply leave for the next calendar year.',
  weekends_between: 'Whether weekends falling between leave dates are counted.',
  holidays_between: 'Whether holidays falling between leave dates are counted.',
}
