"""
Standard India payroll components seeded for every organization.

HR assigns amounts on each employee's salary structure; statutory deductions (PF, ESI, PT, TDS)
are computed automatically on pay run from Statutory settings.
"""

INDIA_STANDARD_PAYROLL_COMPONENTS = [
    # —— Gross salary (employee payslip earnings) ——
    {
        "code": "BASIC",
        "name": "Basic salary",
        "category": "basic_structure",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": True,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "DEARNESS_ALLOWANCE",
        "name": "Dearness allowance (DA)",
        "category": "basic_structure",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": True,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "HRA",
        "name": "House rent allowance (HRA)",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "LTA",
        "name": "Leave travel allowance (LTA)",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "CEA",
        "name": "Children education allowance (CEA)",
        "category": "recurring",
        "kind": "earning",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "MEAL_ALLOWANCE",
        "name": "Meal / food allowance",
        "category": "recurring",
        "kind": "earning",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "MOBILE_INTERNET",
        "name": "Mobile / internet reimbursement",
        "category": "adhoc",
        "kind": "earning",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "UNIFORM_ALLOWANCE",
        "name": "Uniform / dress allowance",
        "category": "adhoc",
        "kind": "earning",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "SPECIAL_ALLOWANCE",
        "name": "Special allowance",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": True,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "VARIABLE_PAY",
        "name": "Variable / performance pay",
        "category": "variable",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "TRANSPORT_ALLOWANCE",
        "name": "Transport allowance",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "MEDICAL_ALLOWANCE",
        "name": "Medical allowance",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "CONVEYANCE",
        "name": "Conveyance allowance",
        "category": "recurring",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": True,
        "is_system": True,
    },
    {
        "code": "BONUS",
        "name": "Bonus",
        "category": "adhoc",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "INCENTIVE",
        "name": "Incentive",
        "category": "variable",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "OVERTIME",
        "name": "Overtime",
        "category": "variable",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "ARREARS",
        "name": "Arrears",
        "category": "adhoc",
        "kind": "earning",
        "taxable": True,
        "pf_wage_part": False,
        "esi_wage_part": True,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    # —— Employee deductions (labels; PF/ESI/PT/TDS computed on pay run) ——
    {
        "code": "PF",
        "name": "Provident Fund (employee)",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "ESI",
        "name": "Employee State Insurance (ESI)",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "PT",
        "name": "Professional tax",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "TDS",
        "name": "TDS (income tax)",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "LOAN_RECOVERY",
        "name": "Loan recovery",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
    {
        "code": "SALARY_ADVANCE",
        "name": "Salary advance recovery",
        "category": "statutory",
        "kind": "deduction",
        "taxable": False,
        "pf_wage_part": False,
        "esi_wage_part": False,
        "prorate_with_attendance": False,
        "is_system": True,
    },
]


def seed_standard_components_for_organization(organization, PayrollComponent):
    """Create any missing standard components for an organization."""
    for row in INDIA_STANDARD_PAYROLL_COMPONENTS:
        PayrollComponent.objects.get_or_create(
            organization=organization,
            code=row["code"],
            defaults=row,
        )
