# Generated by Django 6.0.4 on 2026-05-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_officelocationsettings_organization_and_more'),
        ('leave_management', '0002_leavepolicy_leavepolicyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='employees.organization'),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_leave_policy_name_per_org'),
        ),
    ]
