# Generated by Django 6.0.4 on 2026-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_accrual_halfyearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day',
            field=models.CharField(choices=[('none', 'None'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='none', max_length=20),
        ),
    ]
