# Generated by Django 6.0.4 on 2026-07-29 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employeedocument_file'),
        ('leave_management', '0007_leaverequest_half_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('quota', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_overrides', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='uniq_leave_override_emp_type_year')],
            },
        ),
    ]
