# Generated by Django 6.0.4 on 2026-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_leavebalanceoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalanceoverride',
            name='used_adjustment',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
