# Generated by Django 6.0.4 on 2026-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_leavebalanceoverride_used_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceoverride',
            name='quota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
