# Generated by Django 6.0.4 on 2026-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_alter_leavebalanceoverride_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalanceoverride',
            name='carry_forward',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
