# Generated by Django 6.0.4 on 2026-08-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employeedocument_file'),
        ('leave_management', '0011_leavebalanceoverride_carry_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='employees.organization')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='unique_holiday_per_org_date')],
            },
        ),
    ]
