# Generated by Django 6.0.4 on 2026-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employeedocument_file'),
        ('leave_management', '0012_holiday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holiday',
            name='unique_holiday_per_org_date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='applicable_shifts',
            field=models.ManyToManyField(blank=True, help_text='If empty, applies to all shifts', related_name='holidays', to='employees.shifttemplate'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'date'), name='unique_holiday_per_org_name_date'),
        ),
    ]
