# Generated by Django 6.0.4 on 2026-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0013_remove_holiday_unique_holiday_per_org_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
