import threading
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action
from rest_framework.response import Response
from django.db.models import Q
from accounts.async_tasks import send_html_email_async
from .models import Ticket, TicketMessage, TicketStatus, PlatformTicket, PlatformTicketMessage
from .serializers import TicketSerializer, TicketMessageSerializer, PlatformTicketSerializer, PlatformTicketMessageSerializer
from employees.models import Employee
from accounts.models import AppNotification, User

def notify_user(user, title, message, notif_type="helpdesk"):
    AppNotification.objects.create(
        user=user,
        title=title,
        message=message,
        type=notif_type
    )

def _simulate_ai_l1_support(ticket_id):
    """Background task to simulate AI reading the ticket and responding."""
    try:
        ticket = Ticket.objects.get(id=ticket_id)
        bot_user, _ = User.objects.get_or_create(email="ai_bot@system.local", defaults={"first_name": "AI", "last_name": "Support Bot", "role": "admin"})
        response_msg = (
            "Hello! I am your AI Support Assistant. I've analyzed your ticket regarding '{}'.\n\n"
            "Based on our company policies, please ensure you have checked the relevant documentation on your dashboard. "
            "If this is a payroll issue, payslips are usually generated by the 5th of every month. "
            "For IT issues, have you tried restarting your device?\n\n"
            "Did this resolve your issue, or would you like me to escalate this to a human HR/Admin representative?"
        ).format(ticket.title)
        
        TicketMessage.objects.create(
            ticket=ticket,
            sender=bot_user,
            message=response_msg,
            is_ai=True
        )
        
        # Notify the employee
        notify_user(ticket.employee.user, "AI Assistant Replied", f"AI responded to your ticket: {ticket.title}", f"helpdesk_{ticket.id}")
    except Exception as e:
        print("AI Bot error:", e)

class TicketViewSet(viewsets.ModelViewSet):
    serializer_class = TicketSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        qs = Ticket.objects.select_related('employee', 'employee__user', 'assigned_to').prefetch_related('messages', 'messages__sender')
        if user.is_superuser or user.role in ["admin", "hr", "owner"]:
            return qs.all().order_by('-created_at')
        return qs.filter(employee__user=user).order_by('-created_at')

    def perform_create(self, serializer):
        user = self.request.user
        try:
            employee = Employee.objects.get(user=user)
        except Employee.DoesNotExist:
            if user.role in ["admin", "hr", "owner", "manager", "hr_admin", "org_admin"] or user.is_superuser:
                employee = Employee.objects.create(
                    user=user,
                    organization=getattr(user, 'organization', None),
                    employee_code=f"ADMIN-{user.id}"
                )
            else:
                from rest_framework.exceptions import ValidationError
                raise ValidationError({"detail": "Employee profile required."})
                
        ticket = serializer.save(employee=employee)
        
        # Simulate AI support synchronously to avoid thread lifecycle issues in development servers
        _simulate_ai_l1_support(ticket.id)

    @action(detail=True, methods=['patch'])
    def update_status(self, request, pk=None):
        user = request.user
        ticket = self.get_object()
        new_status = request.data.get('status')
        
        if new_status == 'escalated' and ticket.employee.user == user:
            # Employee escalates
            ticket.status = new_status
            ticket.save()
            # Notify HR/Admin
            hr_users = User.objects.filter(role__in=["admin", "hr"])
            for hr in hr_users:
                notify_user(hr, "Ticket Escalated", f"Ticket #{ticket.id} escalated to human support.", f"helpdesk_{ticket.id}")
            return Response(TicketSerializer(ticket).data)
            
        if not (user.is_superuser or user.role in ["admin", "hr", "owner"]):
            return Response({"detail": "Not authorized."}, status=status.HTTP_403_FORBIDDEN)
            
        if new_status and new_status in [c[0] for c in TicketStatus.choices]:
            ticket.status = new_status
            ticket.save()
            # Notify employee of status change
            notify_user(ticket.employee.user, "Ticket Status Updated", f"Your ticket '{ticket.title}' is now {new_status.replace('_', ' ')}.", f"helpdesk_{ticket.id}")
            return Response(TicketSerializer(ticket).data)
            
        return Response({"detail": "Invalid status."}, status=status.HTTP_400_BAD_REQUEST)

class TicketMessageViewSet(viewsets.ModelViewSet):
    serializer_class = TicketMessageSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if self.action in ['retrieve', 'update', 'partial_update', 'destroy']:
            if user.is_superuser or user.role in ["admin", "hr", "owner"]:
                return TicketMessage.objects.all()
            return TicketMessage.objects.filter(ticket__employee__user=user)
            
        ticket_id = self.request.query_params.get('ticket')
        if not ticket_id:
            return TicketMessage.objects.none()
        try:
            ticket = Ticket.objects.get(id=ticket_id)
        except Ticket.DoesNotExist:
            return TicketMessage.objects.none()
            
        if not (user.is_superuser or user.role in ["admin", "hr", "owner"]) and ticket.employee.user != user:
            return TicketMessage.objects.none()
                
        return TicketMessage.objects.filter(ticket_id=ticket_id).order_by('created_at')

    def destroy(self, request, *args, **kwargs):
        msg = self.get_object()
        if request.user.is_superuser or request.user.role in ["admin", "hr", "owner"] or msg.sender == request.user:
            return super().destroy(request, *args, **kwargs)
        from rest_framework.exceptions import PermissionDenied
        raise PermissionDenied("You can only delete your own messages.")

    def perform_create(self, serializer):
        user = self.request.user
        ticket_id = self.request.data.get('ticket')
        ticket = Ticket.objects.get(id=ticket_id)
        if not (user.is_superuser or user.role in ["admin", "hr", "owner"]) and ticket.employee.user != user:
            from rest_framework.exceptions import PermissionDenied
            raise PermissionDenied("Access denied.")
            
        msg = serializer.save(sender=user, ticket=ticket)
        
        # Notifications & AI Bot Multi-Turn
        if ticket.employee.user == user:
            # AI Bot Multi-turn logic
            if ticket.status not in ["escalated", "closed", "resolved"]:
                bot_user, _ = User.objects.get_or_create(email="ai_bot@system.local", defaults={"first_name": "AI", "last_name": "Support Bot", "role": "admin"})
                msg_lower = msg.message.lower()
                
                if any(word in msg_lower for word in ["human", "hr", "admin", "escalate", "help"]):
                    ticket.status = 'escalated'
                    ticket.save()
                    TicketMessage.objects.create(
                        ticket=ticket,
                        sender=bot_user,
                        message="I have successfully escalated this ticket to our human HR/Admin team. They will assist you shortly.",
                        is_ai=True
                    )
                    for hr in User.objects.filter(role__in=["admin", "hr"]):
                        notify_user(hr, "Ticket Escalated", f"Ticket #{ticket.id} was auto-escalated by AI.", f"helpdesk_{ticket.id}")
                else:
                    TicketMessage.objects.create(
                        ticket=ticket,
                        sender=bot_user,
                        message="I'm still learning! If my previous answer didn't help, please provide more details, or click 'Escalate to HR/Admin' below to speak to a human.",
                        is_ai=True
                    )
            else:
                # Normal human-to-human notification
                if ticket.assigned_to:
                    notify_user(ticket.assigned_to, "New Ticket Message", f"New message from {user.first_name} on Ticket #{ticket.id}", f"helpdesk_{ticket.id}")
                else:
                    for hr in User.objects.filter(role__in=["admin", "hr"]):
                        notify_user(hr, "New Ticket Message", f"New message on Ticket #{ticket.id}", f"helpdesk_{ticket.id}")
        else:
            # Notify employee
            notify_user(ticket.employee.user, "New Support Reply", f"HR replied to your ticket '{ticket.title}'", f"helpdesk_{ticket.id}")

class PlatformTicketViewSet(viewsets.ModelViewSet):
    serializer_class = PlatformTicketSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return PlatformTicket.objects.all().order_by('-created_at')
        return PlatformTicket.objects.filter(organization=getattr(user, 'organization', None)).order_by('-created_at')

    def perform_create(self, serializer):
        user = self.request.user
        serializer.save(
            created_by=user, 
            organization=getattr(user, 'organization', None)
        )
        title = serializer.validated_data.get('title')
        # Notify superusers
        for su in User.objects.filter(is_superuser=True):
            notify_user(su, "New Platform Ticket", f"Tenant raised a ticket: {title}", f"platform_{serializer.instance.id if serializer.instance else ''}")
            
            # Send Email
            email_to = su.contact_email or su.email
            if email_to:
                org_name = getattr(user.organization, 'name', 'Unknown Organization') if user.organization else 'Unknown Organization'
                html_body = f"""
                <p>Hello {su.first_name or 'Super Admin'},</p>
                <p>A new platform support ticket has been raised by <strong>{user.first_name} {user.last_name}</strong> from <strong>{org_name}</strong>.</p>
                <p><strong>Title:</strong> {title}</p>
                <p>Please log in to the Platform Owner Dashboard to view and reply.</p>
                """
                send_html_email_async(
                    to_email=email_to,
                    subject=f"New Platform Support Ticket: {title}",
                    html=html_body
                )
                
        # Send confirmation email to the user who raised the ticket
        if user.email:
            tenant_html_body = f"""
            <p>Hello {user.first_name},</p>
            <p>We have successfully received your platform support ticket: <strong>{title}</strong>.</p>
            <p>Our team at Worksphere has been notified and will review your request shortly. We will contact you as soon as there is an update.</p>
            <p>Thank you,</p>
            <p>Worksphere</p>
            """
            send_html_email_async(
                to_email=user.email,
                subject=f"Ticket Received: {title}",
                html=tenant_html_body
            )

    @action(detail=True, methods=['patch'])
    def update_status(self, request, pk=None):
        if not request.user.is_superuser:
            return Response(status=status.HTTP_403_FORBIDDEN)
        ticket = self.get_object()
        new_status = request.data.get('status')
        if new_status and new_status in [c[0] for c in TicketStatus.choices]:
            ticket.status = new_status
            ticket.save()
            notify_user(ticket.created_by, "Platform Ticket Updated", f"Status changed to {new_status}", f"platform_{ticket.id}")
            return Response(PlatformTicketSerializer(ticket).data)
        return Response(status=400)

class PlatformTicketMessageViewSet(viewsets.ModelViewSet):
    serializer_class = PlatformTicketMessageSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if self.action in ['retrieve', 'update', 'partial_update', 'destroy']:
            if user.is_superuser:
                return PlatformTicketMessage.objects.all()
            return PlatformTicketMessage.objects.filter(ticket__organization=getattr(user, 'organization', None))
            
        ticket_id = self.request.query_params.get('ticket')
        if not ticket_id:
            return PlatformTicketMessage.objects.none()
        try:
            ticket = PlatformTicket.objects.get(id=ticket_id)
        except PlatformTicket.DoesNotExist:
            return PlatformTicketMessage.objects.none()
        if not user.is_superuser and ticket.organization != getattr(user, 'organization', None):
            return PlatformTicketMessage.objects.none()
        return PlatformTicketMessage.objects.filter(ticket_id=ticket_id).order_by('created_at')

    def destroy(self, request, *args, **kwargs):
        msg = self.get_object()
        if request.user.is_superuser or msg.sender == request.user:
            return super().destroy(request, *args, **kwargs)
        from rest_framework.exceptions import PermissionDenied
        raise PermissionDenied("You can only delete your own messages.")

    def perform_create(self, serializer):
        user = self.request.user
        ticket = PlatformTicket.objects.get(id=self.request.data.get('ticket'))
        if not user.is_superuser and ticket.organization != getattr(user, 'organization', None):
            from rest_framework.exceptions import PermissionDenied
            raise PermissionDenied("Access denied.")
            
        serializer.save(sender=user, ticket=ticket)
        if user.is_superuser:
            notify_user(ticket.created_by, "Platform Support Reply", f"Super Admin replied to your ticket", f"platform_{ticket.id}")
        else:
            for su in User.objects.filter(is_superuser=True):
                notify_user(su, "New Platform Message", f"New message on Platform Ticket #{ticket.id}", f"platform_{ticket.id}")
                
                # Send Email
                email_to = su.contact_email or su.email
                if email_to:
                    org_name = getattr(user.organization, 'name', 'Unknown Organization') if user.organization else 'Unknown Organization'
                    html_body = f"""
                    <p>Hello {su.first_name or 'Super Admin'},</p>
                    <p><strong>{user.first_name} {user.last_name}</strong> from <strong>{org_name}</strong> sent a new message on Platform Ticket #{ticket.id}: <em>{ticket.title}</em>.</p>
                    <p>Please log in to the Platform Owner Dashboard to view and reply.</p>
                    """
                    send_html_email_async(
                        to_email=email_to,
                        subject=f"New Message on Platform Ticket #{ticket.id}",
                        html=html_body
                    )
