# Generated by Django 6.0.4 on 2026-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecorrectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='request_type',
            field=models.CharField(choices=[('mark_present', 'Mark present'), ('mark_leave', 'Mark leave'), ('manual_review', 'Manual review')], default='mark_present', max_length=20),
        ),
    ]
