# Generated by Django 6.0.4 on 2026-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancecorrectionrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='request_type',
            field=models.CharField(choices=[('mark_present', 'Mark present'), ('mark_exact_time', 'Mark exact time'), ('mark_leave', 'Mark leave'), ('manual_review', 'Manual review')], default='mark_present', max_length=20),
        ),
    ]
