# Generated by Django 6.0.4 on 2026-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenseclaim_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='skip_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
