# Generated by Django 6.0.4 on 2026-05-12 06:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_organization_employee_organization"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(blank=True, max_length=16)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('bank_ifsc', models.CharField(blank=True, max_length=16)),
                ('pf_eligible', models.BooleanField(default=True)),
                ('esi_eligible', models.BooleanField(default=True)),
                ('pt_applicable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_profiles', to='employees.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('basic_structure', 'Basic structure'), ('recurring', 'Recurring'), ('variable', 'Variable'), ('adhoc', 'Adhoc'), ('statutory', 'Statutory')], default='recurring', max_length=32)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=16)),
                ('taxable', models.BooleanField(default=True)),
                ('pf_wage_part', models.BooleanField(default=False, help_text='Include prorated amount in PF wage (before monthly ceiling).')),
                ('esi_wage_part', models.BooleanField(default=False, help_text='Include prorated amount in gross used for ESI eligibility and calculation.')),
                ('prorate_with_attendance', models.BooleanField(default=True, help_text='If false, full monthly amount applies (e.g. some variable payouts).')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded components; cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='employees.organization')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'Fixed monthly'), ('percent_basic', 'Percent of basic')], default='fixed', max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed component amount, or ignored when using percent_basic.', max_digits=12)),
                ('percent_of_basic', models.DecimalField(blank=True, decimal_places=4, help_text='When mode is percent_basic: % of resolved monthly basic.', max_digits=8, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lines', to='employees.employee')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary_lines', to='payroll.payrollcomponent')),
            ],
            options={
                'ordering': ['employee_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEmployeeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('is_on_hold', models.BooleanField(default=False)),
                ('tds_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_monthly_full', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gross_prorated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_prorated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_statutory_and_taxes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_results', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollResultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=16)),
                ('amount_full_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount_prorated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_result_lines', to='payroll.payrollcomponent')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollemployeeresult')),
            ],
            options={
                'ordering': ['result_id', 'kind', 'component__code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('working_days', models.PositiveSmallIntegerField(default=22, help_text='Paid-day denominator for proration (pay register).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='employees.organization')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payrollemployeeresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_results', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayrollStatutoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_enabled', models.BooleanField(default=True)),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('pf_monthly_wage_ceiling', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='EPFO wage ceiling for contribution (commonly ₹15,000/mo; verify current law).', max_digits=12)),
                ('esi_enabled', models.BooleanField(default=True)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('3.25'), max_digits=5)),
                ('esi_gross_threshold', models.DecimalField(decimal_places=2, default=Decimal('21000.00'), help_text='ESI applies when gross is at or below this (configurable).', max_digits=12)),
                ('esi_basis', models.CharField(choices=[('gross', 'Prorated gross (earnings)'), ('pf_wage', 'PF wage')], default='gross', max_length=16)),
                ('professional_tax_monthly', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Flat PT per month when applicable (state slabs can be layered later).', max_digits=10)),
                ('tds_regime', models.CharField(choices=[('old', 'Old regime (India)'), ('new', 'New regime (India)')], default='old', max_length=8)),
                ('standard_deduction_annual', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('include_cess_on_tds_estimate', models.BooleanField(default=True, help_text='Apply 4% health & education cess on estimated annual tax, spread monthly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_statutory', to='employees.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2025-26', max_length=9)),
                ('section_80c', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('section_80d', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_chapter_vi_a', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_declarations', to='employees.employee')),
            ],
            options={
                'ordering': ['-financial_year', 'employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollcomponent',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_payroll_component_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organization', 'period_year', 'period_month'), name='uniq_payroll_run_period_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payrollemployeeresult',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uniq_payroll_result_run_employee'),
        ),
        migrations.AddConstraint(
            model_name='payrolltaxdeclaration',
            constraint=models.UniqueConstraint(fields=('employee', 'financial_year'), name='uniq_tax_declaration_employee_fy'),
        ),
    ]
