# Generated by Django 6.0.4 on 2026-06-17 10:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_statutory_config_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='template_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='compensationrevision',
            name='ctc_type',
            field=models.CharField(choices=[('gross', 'Monthly gross (in-hand)'), ('monthly', 'Monthly CTC'), ('annual', 'Annual CTC')], default='monthly', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='ctc_type',
            field=models.CharField(choices=[('gross', 'Monthly gross (in-hand)'), ('monthly', 'Monthly CTC'), ('annual', 'Annual CTC')], default='gross', max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollctctemplate',
            name='variable_pay_pct_of_ctc',
            field=models.DecimalField(decimal_places=4, default=Decimal('3.3333'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=16),
        ),
    ]
