# Generated by Django 6.0.4 on 2026-09-02 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_employeecompensation_template_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployeeresult',
            name='scheduled_weekends',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='payrollemployeeresult',
            name='scheduled_working_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
