# Generated by Django 6.0.4 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_bonusincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusincentive',
            name='custom_type',
            field=models.CharField(blank=True, help_text="Custom name if type is 'other'", max_length=80),
        ),
        migrations.AlterField(
            model_name='bonusincentive',
            name='type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('incentive', 'Incentive'), ('other', 'Other')], max_length=16),
        ),
    ]
