# Generated by Django 6.0.4 on 2026-09-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_bonusincentive_custom_type_alter_bonusincentive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollresultline',
            name='epoch_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
