# Generated by Django 6.0.4 on 2026-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional — used for birthday widgets and celebrations.', null=True),
        ),
    ]
