# Generated by Django 6.0.4 on 2026-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Allowed late buffer (minutes) before marking late.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Scheduled shift end time for anomaly checks.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Scheduled shift start time for anomaly checks.', null=True),
        ),
    ]
