# Generated by Django 6.0.4 on 2026-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_shift_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed late buffer (minutes) before marking late.'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
