# Generated by Django 6.0.4 on 2026-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_grace_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_radius_meters',
            field=models.PositiveIntegerField(default=200, help_text='Allowed radius around office location for attendance actions.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_restriction_enabled',
            field=models.BooleanField(default=True, help_text='If true, check-in/check-out allowed only near office location.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
