# Generated by Django 6.0.4 on 2026-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_officelocationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='early_checkout_grace_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Allowed early checkout buffer (minutes) before marking anomaly.'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='early_checkout_grace_minutes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
