# Generated by Django 6.0.4 on 2026-05-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_organization_employee_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocationsettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_location', to='employees.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap for subscription enforcement (future).', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='employees.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.organization'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_code'), name='uniq_employee_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_shift_template_name_per_org'),
        ),
    ]
