# Generated by Django 6.0.4 on 2026-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_shifttemplate_kredily_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='auto_clock_out_after_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minutes after scheduled shift end to auto clock-out (div=0 means at shift end).'),
        ),
    ]
