# Generated by Django 6.0.4 on 2026-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_shifttemplate_auto_clock_out_after_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization_signatures/'),
        ),
    ]
