# Generated by Django 6.0.4 on 2026-07-15 05:27

from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import migrations, models

try:
    import cloudinary_storage.storage
    _document_storage = cloudinary_storage.storage.RawMediaCloudinaryStorage()
except Exception:
    # Cloudinary not configured (e.g. local dev without env vars) — fall back
    # to the default storage so migrations can still run.
    _document_storage = FileSystemStorage()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_organization_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(storage=_document_storage, upload_to='employee_docs/'),
        ),
    ]
