# Generated by Django 6.0.4 on 2026-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
    ]
