# Generated by Django 6.0.4 on 2026-09-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_organization_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='expense_backdate_limit_days',
            field=models.PositiveIntegerField(blank=True, help_text='Max days in the past an expense can be incurred. Leave blank for unlimited.', null=True),
        ),
    ]
