# Generated by Django 6.0.4 on 2026-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_organization_expense_backdate_limit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email for records, kept even after offboarding.', max_length=254, null=True),
        ),
    ]
