# Generated by Django 6.0.4 on 2026-09-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_organization_seal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='resignation_auto_msg_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic warning message on resignation.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='resignation_auto_msg_text',
            field=models.TextField(blank=True, default='You have to submit all the assets before leaving the office. After submission all then only the resignation is accepted.', help_text='Warning message shown to user when applying for resignation.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='resignation_notice_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Minimum notice period days for resignation.'),
        ),
    ]
