# Generated by Django 6.0.4 on 2026-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_organization_resignation_auto_msg_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
