# Generated by Django 6.0.4 on 2026-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_alter_resignation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='document_watermark',
            field=models.ImageField(blank=True, help_text='Center watermark image for generated documents', null=True, upload_to='organization_branding/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='letterhead_footer',
            field=models.ImageField(blank=True, help_text='Bottom footer image for generated documents (PDF)', null=True, upload_to='organization_branding/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='letterhead_header',
            field=models.ImageField(blank=True, help_text='Top header image for generated documents (PDF)', null=True, upload_to='organization_branding/'),
        ),
    ]
