# Generated by Django 6.0.4 on 2026-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_organization_document_watermark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='document_watermark',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='letterhead_footer',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='letterhead_header',
        ),
        migrations.AddField(
            model_name='organization',
            name='letterhead_background',
            field=models.ImageField(blank=True, help_text='Full page letterhead background image for generated documents', null=True, upload_to='organization_branding/', verbose_name='Letterhead Background'),
        ),
    ]
