# Generated by Django 6.0.4 on 2026-09-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_remove_organization_document_watermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_background_image', models.ImageField(blank=True, null=True, upload_to='id_cards/front/')),
                ('back_background_image', models.ImageField(blank=True, null=True, upload_to='id_cards/back/')),
                ('authorized_signature_image', models.ImageField(blank=True, null=True, upload_to='id_cards/signatures/')),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('show_blood_group', models.BooleanField(default=True)),
                ('show_emergency_contact', models.BooleanField(default=True)),
                ('show_dob', models.BooleanField(default=False)),
                ('show_address', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_template', to='employees.organization')),
            ],
        ),
    ]
