# Generated by Django 6.0.4 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_employee_blood_group_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='terms_conditions',
            field=models.TextField(blank=True, default='This card is the property of the company. If found, please return to the company address.'),
        ),
    ]
