# Generated by Django 6.0.4 on 2026-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_idcardtemplate_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_fields_data',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs matching custom_employee_fields in Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_employee_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'name': 'UAN', 'required': True}]"),
        ),
    ]
