# Generated by Django 6.0.4 on 2026-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_employee_custom_fields_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_self_service_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
