# Generated by Django 6.0.4 on 2026-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_organization_profile_self_service_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='saturday_end_time',
            field=models.TimeField(blank=True, help_text='Optional early end time specifically for Saturdays (e.g., 14:00).', null=True),
        ),
    ]
