# Generated by Django 6.0.4 on 2026-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_shifttemplate_saturday_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='attendance_anomaly_backdate_days',
            field=models.PositiveIntegerField(default=3, help_text='Max days in the past an employee can request an attendance correction.'),
        ),
    ]
