# Generated by Django 6.0.4 on 2026-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_organization_attendance_anomaly_backdate_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_attendance_tracked',
            field=models.BooleanField(default=True, help_text="If False, employee is excluded from the daily attendance grid and missing days won't be flagged."),
        ),
    ]
