# Generated by Django 6.0.4 on 2026-10-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('employees', '0034_organization_attendance_anomaly_backdate_days'),
        ('helpdesk', '0002_ticketmessage_is_ai_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_tickets', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.CreateModel(
            name='HelpdeskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_categories', to='employees.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
