# Generated by Django 6.0.4 on 2026-06-25 07:06

import letters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentletter',
            name='pdf_file',
            field=models.FileField(storage=letters.models.get_raw_storage, upload_to='sent_letters/'),
        ),
    ]
