# Generated by Django 6.0.4 on 2026-06-25 07:47

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_sentletter_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentletter',
            name='pdf_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('C:/Users/anish/hrms_project/backend/media')), upload_to='sent_letters/'),
        ),
    ]
