# Generated by Django 6.0.4 on 2026-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_sentletter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentletter',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentletter',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed')], default='sent', max_length=20),
        ),
    ]
