# Generated by Django 6.0.4 on 2026-09-11 07:51

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_sentletter_signed_at_sentletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentletter',
            name='draft_html',
            field=models.TextField(blank=True, help_text='Stores the edited HTML before final PDF generation.'),
        ),
        migrations.AlterField(
            model_name='sentletter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('C:/Users/anish/hrms_project/backend/media')), upload_to='sent_letters/'),
        ),
        migrations.AlterField(
            model_name='sentletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed')], default='draft', max_length=20),
        ),
    ]
