# Generated by Django 6.0.4 on 2026-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_sentletter_draft_html_alter_sentletter_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentletter',
            name='use_letterhead',
            field=models.BooleanField(default=True, help_text="Whether to apply the organization's letterhead background"),
        ),
    ]
