# Generated by Django 6.0.4 on 2026-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_sentletter_use_letterhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='email_message',
            field=models.TextField(blank=True, default='Please find the attached document. We request you to review, sign, and affix the company seal where required. Once completed, please upload the signed copy to your profile.'),
        ),
    ]
